name: lint-pr

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            build
            ci
            docs
            feat
            fix
            perf
            refactor
            test
            infra
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
